// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBsARTf2rTSFqLenPBGHoQm0ulCYHtwl0',
    appId: '1:576870812733:web:31c65afaaa457bc5666e54',
    messagingSenderId: '576870812733',
    projectId: 'pojol-4947f',
    authDomain: 'pojol-4947f.firebaseapp.com',
    storageBucket: 'pojol-4947f.firebasestorage.app',
    measurementId: 'G-XKDW5K9YFT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBsARTf2rTSFqLenPBGHoQm0ulCYHtwl0',
    appId: '1:576870812733:android:31c65afaaa457bc5666e54',
    messagingSenderId: '576870812733',
    projectId: 'pojol-4947f',
    storageBucket: 'pojol-4947f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBsARTf2rTSFqLenPBGHoQm0ulCYHtwl0',
    appId: '1:576870812733:ios:31c65afaaa457bc5666e54',
    messagingSenderId: '576870812733',
    projectId: 'pojol-4947f',
    storageBucket: 'pojol-4947f.firebasestorage.app',
    iosBundleId: 'com.example.pojol',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBsARTf2rTSFqLenPBGHoQm0ulCYHtwl0',
    appId: '1:576870812733:ios:31c65afaaa457bc5666e54',
    messagingSenderId: '576870812733',
    projectId: 'pojol-4947f',
    storageBucket: 'pojol-4947f.firebasestorage.app',
    iosBundleId: 'com.example.pojol',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDBsARTf2rTSFqLenPBGHoQm0ulCYHtwl0',
    appId: '1:576870812733:web:31c65afaaa457bc5666e54',
    messagingSenderId: '576870812733',
    projectId: 'pojol-4947f',
    authDomain: 'pojol-4947f.firebaseapp.com',
    storageBucket: 'pojol-4947f.firebasestorage.app',
    measurementId: 'G-XKDW5K9YFT',
  );
}
